name: Deploy
on:
  push:
    branched:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host server
            HostName flow-visu.suwageeks.org
            User deployer
            Port 21000
            IdentifyFile ~/.ssh/id_rsa
    - name: Run Script
      run: |
        ssh server "cd /home/deployer/Flow-Visu-Front && sh deploy.sh"